# Generated by Django 5.0.1 on 2024-01-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_product_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.IntegerField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='tag',
            field=models.CharField(blank=True, default=False, max_length=200),
        ),
    ]
