# Generated by Django 5.0.1 on 2024-01-16 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_products_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='imagen',
            new_name='image',
        ),
    ]
