# Generated by Django 5.0.1 on 2024-01-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_products_likes_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(blank=True, default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='description2',
            field=models.TextField(blank=True, default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(blank=True, default=False, max_length=200),
        ),
    ]
